### ISSUE TITLE
Working With Maps sample crashes on Windows 11

### ISSUE THREAD

**Issue by jasells** [jsuarezruiz/xamarin-forms-gtk-samples#2]
Looks like it's a `TabbedPage` issue?

Host OS:           Windows 11
GTK# version:   2.12.0.0
Xforms ver    :   3.1.0.697729

Here's the stack trace:
```
at GLib.ExceptionManager.RaiseUnhandledException(Exception e, Boolean is_terminal)
   at Gtk.Widget.shown_cb(IntPtr widget)
   at Gtk.Widget.gtk_widget_show_all(IntPtr raw)
   at Xamarin.Forms.Platform.GTK.Renderers.TabbedPageRenderer.InsertPage(Page page, Int32 index) in D:\a\1\s\Xamarin.Forms.Platform.GTK\Renderers\TabbedPageRenderer.cs:line 150
   at Xamarin.Forms.Platform.GTK.Renderers.TabbedPageRenderer.ResetPages() in D:\a\1\s\Xamarin.Forms.Platform.GTK\Renderers\TabbedPageRenderer.cs:line 175
   at Xamarin.Forms.Platform.GTK.Renderers.TabbedPageRenderer.OnPagesChanged(Object sender, NotifyCollectionChangedEventArgs e) in D:\a\1\s\Xamarin.Forms.Platform.GTK\Renderers\TabbedPageRenderer.cs:line 116
   at Xamarin.Forms.Platform.GTK.Renderers.TabbedPageRenderer.Init() in D:\a\1\s\Xamarin.Forms.Platform.GTK\Renderers\TabbedPageRenderer.cs:line 48
   at Xamarin.Forms.Platform.GTK.Renderers.TabbedPageRenderer.OnElementChanged(VisualElementChangedEventArgs e) in D:\a\1\s\Xamarin.Forms.Platform.GTK\Renderers\TabbedPageRenderer.cs:line 44
   at Xamarin.Forms.Platform.GTK.Renderers.AbstractPageRenderer`2.SetElement(VisualElement element) in D:\a\1\s\Xamarin.Forms.Platform.GTK\Renderers\AbstractPageRenderer.cs:line 62
   at Xamarin.Forms.Platform.GTK.Platform.CreateRenderer(VisualElement element) in D:\a\1\s\Xamarin.Forms.Platform.GTK\Platform.cs:line 95
   at Xamarin.Forms.Platform.GTK.Platform.AddChild(Page mainPage) in D:\a\1\s\Xamarin.Forms.Platform.GTK\Platform.cs:line 136
   at Xamarin.Forms.Platform.GTK.Platform.SetPage(Page newRoot) in D:\a\1\s\Xamarin.Forms.Platform.GTK\Platform.cs:line 124
   at Xamarin.Forms.Platform.GTK.FormsWindow.UpdateMainPage() in D:\a\1\s\Xamarin.Forms.Platform.GTK\FormsWindow.cs:line 113
   at Xamarin.Forms.Platform.GTK.FormsWindow.LoadApplication(Application application) in D:\a\1\s\Xamarin.Forms.Platform.GTK\FormsWindow.cs:line 42
   at WorkingWithMaps.GTK.Program.Main(String[] args) in C:\Source\Repos\xamarin-forms-gtk-samples\WorkingWithMaps\GTK\WorkingWithMaps.GTK\Program.cs:line 18
```

I'll see if XForms upgrade fixes things?

I did get the map to load, if I edit source and only load the mapView, not a tabbedPage that can show different views.

**Comment by jasells** [comment]
Ok, it appears the issue is not the `TabbedPage`, but due to some unimplemented API's for `XForms.Maps.GTK` (Pins, Geocoder, and "native" map-app).  When those tabs are included, the app will crash at different point, either on page load or with user-interaction, depending on which one of the above features is enabled.
